# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: company.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("company.proto", :syntax => :proto3) do
    add_message "chimney_rock.protobuf.Company" do
      optional :id, :int32, 1
      optional :external_id, :string, 2
      optional :name, :string, 3
    end
  end
end

module ChimneyRock
  module Protobuf
    Company = Google::Protobuf::DescriptorPool.generated_pool.lookup("chimney_rock.protobuf.Company").msgclass
  end
end
